CREATE TABLE ALMACEN(NUMERO_ALMACEN INTEGER, UBICACION_ALMACEN VARCHAR2(50), 
                  CONSTRAINT PK_NUM_ALM PRIMARY KEY (NUMERO_ALMACEN));



CREATE TABLE CLIENTE (NUMERO_CLIENTE INTEGER, NUMERO_ALMACEN INTEGER, NOMBRE_CLIENTE VARCHAR2(80),
CONSTRAINT PK_N_C PRIMARY KEY (NUMERO_CLIENTE), 
CONSTRAINT FK1_N_A FOREIGN KEY (NUMERO_ALMACEN) REFERENCES ALMACEN (NUMERO_ALMACEN)); 


CREATE TABLE VENDEDOR (NUMERO_VENDEDOR INTEGER, NOMBRE_VENDEDOR VARCHAR2(40), AREA_VENTAS VARCHAR2 (60), 
  CONSTRAINT PK_NUMERO_VENDEDOR PRIMARY KEY (NUMERO_VENDEDOR));


CREATE TABLE VENTAS (ID_VENTAS INTEGER, NUMERO_CLIENTE INTEGER, NUMERO_VENDEDOR 
INTEGER, MONTO_VENTA FLOAT, 
  --RESTRICCIONES, DONDE PONEMOS LLAVES PRIMARIAS Y FORENEAS, NUMERO CLIENTE ES PK, NUMERO_VENDEDR ES DE TABLA VENTAS O SEA FK Y NUMERO_VENDEDOR ES DE TABLA VENDEDOR ES FK
  CONSTRAINT PK_ID_VENTAS PRIMARY KEY (ID_VENTAS), 
  CONSTRAINT FK1_NUMERO_CLIENTE FOREIGN KEY (NUMERO_CLIENTE) REFERENCES CLIENTE (NUMERO_CLIENTE) ,
  CONSTRAINT FK2_NUMERO_VENDEDOR FOREIGN KEY (NUMERO_VENDEDOR) REFERENCES VENDEDOR (NUMERO_VENDEDOR));








CREATE TABLE CALIFICACIONES (ID_CALIFICACION INTEGER, MATERIA VARCHAR2 (80), VALOR FLOAT, 
  CONSTRAINT PK_ID_CALIFICACION PRIMARY KEY (ID_CALIFICACION));
  
  
  
  CREATE SEQUENCE SEC_CALIFICACIONES 
START WITH 1
INCREMENT BY 1
NOMAXVALUE; -- O SE PUEDE PONER NOMAXVALUE= 1000 Y SOLO LLEGA A 1000 REGISTROS (DEPENDIENDO QUE SE QUIERA)



CREATE OR REPLACE PROCEDURE GUARDAR_CALIFICACIONES (
MY_ID_CALIFICACION OUT INTEGER, MY_MATERIA IN VARCHAR2, MY_VALOR IN FLOAT
)
AS
BEGIN


SELECT SEC_CALIFICACIONES.NEXTVAL INTO  MY_ID_CALIFICACION FROM DUAL;
INSERT INTO CALIFICACIONES VALUES (MY_ID_CALIFICACION, MY_MATERIA, MY_VALOR);
END; 
/


--PROBAR PROCEDIMIENTO--

DECLARE 
VALOR INTEGER; 
BEGIN
GUARDAR_CALIFICACIONES(VALOR, 'BASE DATOS 2', 9);
END;
/


--VERIFICAMOS--

SELECT * FROM CALIFICACIONES;

--PARA BORRAR UNO--

DELETE FROM CALIFICACIONES WHERE ID_CALIFICACION=3;

--PARA CONTAR--
SELECT COUNT (*) FROM CALIFICACIONES;


--EJEMPLO EXPLICITO CON LA TABLA CALIFICACIONES--


DECLARE
CURSOR CUR_CALIF IS SELECT * FROM CALIFICACIONES;
--EN LA LINEA DE CURSOR SE PONE EL NOMBRE DEL CURSOR Y EN DONDE SE EJECUTARÁ
BEGIN
--EMPIEZA LA LOGICA DEL CURSOR
  FOR REC IN CUR_CALIF LOOP --REC=RECORD, FILA O PUEDE SER CUALQUIER NOMBRE MÁS EL NOMBRE DEL CURSOR
  DBMS_OUTPUT.PUT_LINE(' CALIFICACIONES ' ||REC.VALOR|| ' MATERIA ' || REC.MATERIA );
  END LOOP;
  END;
  /
  
  SET SERVEROUTPUT ON; --ESTE SOLO SE EJECUTA UNA VEZ DURANTE TODA LA SESION-
  
  












